CREATE TABLE `p_yuho_growth` (
	`stock_id` integer PRIMARY KEY NOT NULL,
	`ord_years` integer NOT NULL,
	`ord_first_fy` text NOT NULL,
	`ord_last_fy` text NOT NULL,
	`ord_first_orders_yen` integer,
	`ord_last_orders_yen` integer,
	`ord_first_backlog_yen` integer,
	`ord_last_backlog_yen` integer,
	`ord_orders_cagr` real,
	`ord_backlog_cagr` real,
	`ord_orders_yoy` real,
	`ord_backlog_yoy` real,
	`ord_has_year_gap` integer NOT NULL,
	`ovs_years` integer NOT NULL,
	`ovs_first_fy` text NOT NULL,
	`ovs_last_fy` text NOT NULL,
	`ovs_first_overseas_yen` integer,
	`ovs_last_overseas_yen` integer,
	`ovs_last_total_yen` integer,
	`ovs_first_ratio_pct` real,
	`ovs_latest_ratio_pct` real,
	`ovs_overseas_cagr` real,
	`ovs_overseas_yoy` real,
	`ovs_has_year_gap` integer NOT NULL,
	`ovs_has_overseas_total` integer NOT NULL,
	`ovs_region_china_yen` integer,
	`ovs_region_americas_yen` integer,
	`ovs_region_europe_yen` integer,
	`ovs_region_asia_yen` integer,
	`as_of` text NOT NULL,
	`source_max_date` text NOT NULL,
	`computed_at` integer DEFAULT (unixepoch()) NOT NULL
);
